const handler = async (m, { conn }) => {
  conn.reply(m.chat, `*◤ ────「 𝚅 𝙴 𝚁 𝙳 𝙰 𝙳 」──── ◥*

*⚄︎.- ${pickRandom(global.verdad)}*

*◣ ──「  Black Clover 」── ◢*
  `, m, {
    contextInfo: global.rcanal
  });
};

handler.help = ['verdad'];
handler.tags = ['fun'];
handler.command ='verdad', /^verdad/i;
handler.register = true;

export default handler;

function pickRandom(list) {
  return list[Math.floor(Math.random() * list.length)];
}

global.verdad = [
  '¿Con quién experimentaste el amor de verdad?',
  '¿Cómo sería tu cita perfecta?',
  '¿Cuál es tu mayor miedo en la vida?',
  '¿Cuántas veces te han rechazado?',
  '¿Cuál es tu mayor inseguridad?',
  '¿Eres realmente feliz?',
  '¿Sientes que ya cumpliste tu objetivo en la vida?',
  '¿A los cuántos años fue tu primer amor?',
  '¿Alguna vez has tenido una _"aventura"_ con alguien?',
  '¿Te gustaría repetir los últimos 5 años de tu vida?',
  'Actualmente, ¿Quién es la persona más influyente de tu vida?',
  '¿Cuál es tu mayor logro?',
  '¿Te sientes capaz de cumplir todos tus sueños?',
  '¿Cuál es tu más grande sueño?',
  '¿Qué te atrae del sexo opuesto?',
  '¿Qué es lo que le quita lo atractivo a tu sexo opuesto?',
  '¿Qué te causa desagrabilidad en las personas?',
  '¿Tienes alguna enfermedad heredada?',
  '¿Alguna vez has rechazado a alguien? ¿Por qué?',
  '¿Cuál ha sido el momento más vergonzoso de tu vida?',
  '¿Qué logros haz obtenido este año?',
  '¿Cuál es tu peor hábito en el colegio?',
  '¿Cuál es tu peor hábito en tu casa?',
  '¿Te consideras una persona feliz? ¿Por qué?',
  '¿Cuál es la peor cosa que alguien ha inventado sobre ti?',
  '¿Te importan mucho las opiniones ajenas?',
  '¿Qué es lo primero que ves cuando miras a una persona de tu sexo opuesto?',
  '¿Qué es lo que te impide continuar una conversación con alguien?',
  '¿Que es lo mas tonto que has hecho en tu vida?',
  '¿Cómo te gustaría que fuera el último día de tu vida?',
  '¿A qué edad te gustaría fallecer?',
  '¿De verdad amas a tu familia? ¿Por qué?',
  '¿Qué rasgo de ti te gustaría cambiar? ¿Por qué?',
  '¿Qué rasgo de tu amig@ te gustaría cambiar? ¿Por qué?',
  '¿Qué harías si tu novi@ te critica el aspecto físico?',
  '¿En qué piensas antes de dormir?',
  '¿Tienes algún talento oculto? ¿Cuál?',
  '¿Haz manipulado gente para tu beneficio? ¿Por qué?',
  '¿Odias alguna parte de tu cuerpo? ¿Cuál? ¿Por qué?',
  '¿Cuál es tu pasatiempo favorito?',
  'Para ti, ¿Qué es ser feliz?',
  'Define a tu persona con una sola palabra y explica los detalles',
  '¿Alguna película te ha hecho llorar? ¿Cuál?',
  '¿Alguna canción te ha hecho llorar? ¿Cuál?',
  '¿Cuál es tu mayor secreto hasta ahora?',
  '¿Qué ha sido lo más loco que haz hecho por una persona del sexo opuesto?',
  '¿Qué es lo más desagradable que has experimentado?',
  '¿Crees en el amor a primera vista?',
  '¿Cuál sería tu superpoder ideal?',
  '¿Alguien te ha hecho cambiar?',
  '¿Ya tuviste tu _"desarrollo de personaje_"? ¿Cómo fue?',
  '¿Alguna vez has robado algo?',
  '¿Tienes miedo a morir? ¿Por qué?',
  '¿Cuándo fue la última vez que lloraste? ¿Por qué?',
  '¿Cuáles son tus habilidades especiales?',
  '¿Cómo te puede gustar la persona que te gusta?',
  '¿Cómo sabes cuando estás enamorado de una persona?',
  '¿Tienes un gusto culposo? ¿Cuál?',
  '¿Te gustaría casarte algún día?',
  'En tu opinión, ¿Cuál es el peor trabajo que purdes tener? Justifica tu respuesta.',
  '¿Eres virgen?',
  '¿Alguna vez has esperado que la relación de alguien se rompiera? ¿Por qué?',
  '¿Prefieres más amigas o amigos? ¿Por qué?',
  '¿Cómo fue tu mejor cita?',
  '¿Cómo sería _"Tu cita ideal"_?',
  '¿Quién es tu ejemplo a seguir?',
  '¿Te haz enamorado de tu mejor amig@?',
  '¿A los cuántos años fue tu _"primera vez"_?',
  '¿A los cuántos años fue tu primer beso?',
  '¿Cuál ha sido la mejor relación que haz tenido, y por qué se terminó?',
  '¿Te gustaría ser famoso? ¿Por qué?',
  '¿Alguna vez te enamoraste en secreto de algún docente?',
  '¿Cómo te ves en 10 años?',
  '¿Quieres tener hijos?',
  '¿Odias a alguien? ¿Por qué?',
  '¿Actualmente te gusta alguien? ¿Quién y por qué?',
  '¿Ya comiste?',
  '¿Quién es la persona más molesta entre tus amigos? Di la razón.',
  '¿Te gustaría volver a vivir tu niñez? ¿Por qué?',
  '¿Tuviste alguna relación con una ex-pareja de tu amig@?',
  '¿Haz tenido una relación con la pareja de tu amig@?',
  '¿Padre o madre?',
  '¿Eres introvertido, o extrovertido?',
  '¿Alguna vez te han hecho un halago exagerado?',
  '¿Cuál es la peor forma con la que te han querido ligar?',
  '¿Qué es lo primero que harías si te despertaras como alguien del sexo opuesto?',
  '¿Haz resolvido todos tus problemas?',
  '¿Alguna vez dudaste de tu sexualidad?',
  '¿Cuál es la razón más absurda por la que haz terminado una relación?',
  '¿Cuál es el peor hábito que tienes?',
  '¿Cuál crees que es tu mejor característica?',
  '¿Cuál crees que es tu peor característica?',
  '¿Qué es lo más valiente que haz hecho?',
  'Si tuvieras la oportunidad de cambiarte el mombre, ¿Cuál sería tu nuevo nombre?',
  '¿Tienes algún sueño recurrente? ¿Cuál?',
  '¿Cuál sería tu manera de ganar dinero ilegalmente?',
  '¿Sigues haciendo cosas infantiles? ¿Cuáles?',
  '¿Te gustaría ser alguien de tu sexo opuesto?',
  '¿Qué es lo que más te impresiona de la gente?',
  '¿Que es lo que más te decepciona de la gente?',
  '¿Cuál sería una razón por la que irías a prisión?',
  'Si fueras un presidente, ¿Qué ley promulgarías primero?',
  '¿A qué celebridad de gustaría concer en persona?',
  '¿Resucitarías a un muerto? ¿Quién y por qué?',
  '¿Cuál es el mayor error de tu vida?',
  '¿Ya tomaste agua?',
  '¿Haz cometido algún delito?',
  '¿Haz estado en prisión?',
  '¿Crees en la unión libre?',
  '¿Haz tenido un "casi algo"?',
  '¿Alguien te ha traumado?',
  'Si tuvieras la posibilidad de borrar algún acto que hiciste en el pasado, ¿Cuál sería y por qué?',
  '¿Qué es lo peor que le has hecho a alguien?',
  '¿Qué artista/celebridad te atrae y por qué?',
  '¿Actualmente te gusta algún integrante en este chat?',
  '¿Tienes algún amorío/romance con algún integrante de este chat?',
  '¿Ya bañaste?',
  '¿Cuál es tu fantasía sexual más oscura?',
  '¿Tienes algún fetiche? ¿Cuál?',
  '¿Cuál es el mejor regalo que haz recibido?',
  '¿Cuál es la mayor desilusión de tu vida?',
  '(Hombres) ¿Te sientes cómodo con tu _"tamaño"_?',
  'De este chat, ¿A quién te gustaría ver desnud@?',
  '¿Por qué eres amigo de tu amigo?',
  '¿Alguna vez has tenido un sueño erótico con algún integrante de este chat? ¿Quién?',
  '¿Cómo sería tu tatuaje ideal?',
  'Para ti, ¿Qué es más importante en una relación? ¿El sexo, o el amor?',
  '¿Crees que el sexo es genial, bueno, bueno, divertido a veces, o realmente no te importa?',
  '¿Qué te hace realmente amar a alguien?',
  '¿Qué animal se adapta mejor a ti y por qué?',
  '¿Cuál ha sido tu peor cita?',
  '¿Te gustaría besar a alguien ahora? ¿A quién?',
  '¿Te consideras una persona _"fiel"_?',
  '¿Cómo fue tu primer romance adolescente?',
  '¿Cómo te enamoraste por primera vez?',
  '¿Con qué celebridad te gustaría tomar un café?',
  '¿Prefieres cosas materiales, o sentimentales?',
  'De este chat, ¿Quién consideras que es el más atractivo físicamente?',
  'De este chat, ¿Con quién tendrías una _"aventura"_?',
  'De este chat, ¿A quién consideran como el más divertido?',
  '¿Cuál ha sido la experiencia más vergonzosa que has tenido en una cita?',
  '¿Ha estado alguna vez en contacto con drogas?',
  '¿Cuándo fue la última vez que estuviste ebrio?',
  '¿Alguna vez has hecho trampa en un examen escolar?',
  '¿Has robado algo en el pasado?',
  '¿Roncas por la noche?',
  '¿Cuales tu cancion favorita?',
  '¿Tienes un apodo? ¿Cuál?',
  '¿Cuánto tiempo pasas mirándote en el espejo?',
  '(Mujeres) ¿El _"tamaño"_ importa?',
  '¿Cuántas veces a la semana / mes tiene relaciones sexuales y con qué frecuencia desea tener relaciones sexuales?',
  '¿Con cuántas parejas sexuales te has acostado?',
  '¿Cuántas veces te masturbas a la semana?',
  '¿Cómo, dónde y con quién fue tu _"primera vez"_?',
  '¿Qué importancia tienen para ti los _"juegos previos prolongados_"?',
  '¿Qué debe hacer un hombre o una mujer para provocarte sexualmente?',
  '¿Alguna vez has tenido sexo con un amigo cercano?',
  '¿Tienes alguna posición sexual favorita? ¿Cuál?',
  '¿Arriba o abajo?',
  '¿Alguna vez practicaste sexo oral?',
  '¿Peluda o depilada?',
  '¿Haz tenido alguna videollamada hot?',
  '¿Haz hecho intercambios de _"pack"_?',
  '¿Cuándo fue la última vez que tuviste sexo?',
  '¿Te gusta el sexo casual?',
  '¿Disfrutas de tu sexualidad?',
  '¿Cuál ha sido el lugar más raro donde haz tenido relaciones sexuales?',
  '¿Cuál es el lugar más raro donde te gustaría tener relaciones sexuales?',
  '¿Haz mirado pornografía con tu pareja?',
  '¿Tienes algún juguete sexual entre tus pertenencias?',
  '¿Prefieres parado, o acostado?',
  '¿Con la luz encendida, o apagada?',
  '¿Prefieres lento y romántico, o duro y agresivo?',
  '¿Te consideras alguien sexualmente dominante?',
  'De los integrantes de este chat, ¿Con quién te gustaría tener relaciones?',
  'Si no fueras pendejo, ¿Qué te gustaría ser?',
  '¿Tienes carro?',
  '¿Haz mirado pornografía con tu pareja?',
  '¿Tienes algún juguete sexual entre tus pertenencias?',
  '¿Prefieres parado, o acostado?',
  '¿Con la luz encendida, o apagada?',
  '¿Prefieres lento y romántico, o duro y agresivo?',
  '¿Te consideras alguien sexualmente dominante?',
  'De los integrantes de este chat, ¿Con quién te gustaría tener relaciones?',
  'Si no fueras pendejo, ¿Qué te gustaría ser?',
  '¿Tienes carro?',
  '¿Te atreverías a enviarle una foto hot a Elvis SF?',
  '¿Cuál sería tu lugar favorito para hacerlo con Elvis SF?',
  '¿Prefieres besos largos o mordiscos juguetones con Elvis SF?',
  '¿Te gusta tomar el control o que Elvis SF lo haga?',
  '¿Cuál es tu fantasía más secreta con Elvis SF?',
  '¿Te gustaría probar disfraces con Elvis SF?',
  '¿Alguna vez has fantaseado con Elvis SF en público?',
  '¿Prefieres hacerlo rápido o disfrutar cada segundo con Elvis SF?',
  '¿Te gusta el sexting con Elvis SF?',
  '¿Has pensado en usar algún juguete sexual con Elvis SF?',
  '¿Prefieres caricias suaves o fuertes con Elvis SF?',
  '¿Te excita más la voz de Elvis SF o su mirada?',
  '¿Has tenido sueños hot con Elvis SF?',
  '¿Te gustaría probar posiciones nuevas con Elvis SF?',
  '¿Prefieres hacerlo de día o de noche con Elvis SF?',
  '¿Te gusta morder o que te muerdan Elvis SF?',
  '¿Cuál es la parte del cuerpo de Elvis SF que más te gusta?',
  '¿Te atreverías a besar a Elvis SF frente a todos?',
  '¿Te gusta que Elvis SF te susurre cosas al oído?',
  '¿Alguna vez le has enviado un mensaje subido de tono a Elvis SF?',
  '¿Prefieres hacerlo lento y sensual o rápido y apasionado con Elvis SF?',
  '¿Te excita más pensar en Elvis SF desnudo o vestido?',
  '¿Has imaginado hacerlo en lugares prohibidos con Elvis SF?',
  '¿Te atreverías a un juego de roles con Elvis SF?',
  '¿Cuál es tu zona erógena favorita que Elvis SF debería tocar primero?',
  '¿Te gustaría que Elvis SF te sorprendiera con un beso hot?',
  '¿Prefieres caricias ligeras o intensas con Elvis SF?',
  '¿Alguna vez has fantaseado con que Elvis SF te haga un striptease?',
  '¿Te gusta que Elvis SF te tome de la cintura mientras te besa?',
  '¿Has pensado en un masaje sensual con Elvis SF?',
  '¿Te gustaría experimentar con hielo o aceite con Elvis SF?',
  '¿Te excita más que Elvis SF te mire o que te toque?',
  '¿Prefieres que Elvis SF te domine o que tú domines?',
  '¿Cuál es tu outfit más sexy para Elvis SF?',
  '¿Te atreverías a un juego de miradas hot con Elvis SF?',
  '¿Alguna vez has pensado en hacerlo en un auto con Elvis SF?',
  '¿Te excita la idea de recibir un mensaje provocativo de Elvis SF en público?',
  '¿Prefieres empezar besando los labios o el cuello con Elvis SF?',
  '¿Te gustaría probar caricias con los ojos vendados con Elvis SF?',
  '¿Has imaginado que Elvis SF te susurre palabras hot mientras lo haces?',
  '¿Te excita más pensar en Elvis SF haciendo sonidos o movimientos específicos?',
  '¿Prefieres hacerlo en silencio o con gemidos apasionados con Elvis SF?',
  '¿Alguna vez has tenido fantasías de dominación con Elvis SF?',
  '¿Te atreverías a probar nuevas posiciones con Elvis SF sin miedo?',
  '¿Te gustaría que Elvis SF te acariciara mientras ves tu serie favorita?',
  '¿Cuál es tu juguete sexual favorito que usarías con Elvis SF?',
  '¿Te excita que Elvis SF te muestre su lado más travieso?',
  '¿Has pensado en hacerlo con ropa interior sexy con Elvis SF?',
  '¿Te atreverías a probar un juego de temperaturas con Elvis SF?',
  '¿Prefieres hacerlo en la cama o en otro lugar con Elvis SF?',
  '¿Te excita la idea de recibir un mensaje subido de tono de Elvis SF a media noche?',
  '¿Te gustaría que Elvis SF te enseñara algo nuevo en la intimidad?',
  '¿Alguna vez has imaginado un encuentro hot sorpresa con Elvis SF?',
  '¿Te atreverías a enviarle un video hot a Elvis SF?',
  '¿Cuál es tu fantasía más salvaje con Elvis SF?',
  '¿Te gustaría que Elvis SF te tocara en público?',
  '¿Prefieres que Elvis SF te haga un striptease o tú a él?',
  '¿Te excita que Elvis SF te muerda suavemente?',
  '¿Alguna vez has imaginado un threesome con Elvis SF y otra persona?',
  '¿Te gustaría probar juegos de dominación con Elvis SF?',
  '¿Cuál es tu parte favorita del cuerpo de Elvis SF para besar?',
  '¿Te excita que Elvis SF te susurre cosas traviesas al oído?',
  '¿Te atreverías a hacer un juego de roles con Elvis SF?',
  '¿Prefieres sexo rápido o lento y apasionado con Elvis SF?',
  '¿Alguna vez has fantaseado con Elvis SF en un lugar prohibido?',
  '¿Te gusta la idea de caricias subidas de tono en la ducha con Elvis SF?',
  '¿Has imaginado un beso largo y húmedo con Elvis SF?',
  '¿Prefieres que Elvis SF te domine o que tú domines?',
  '¿Te excita que Elvis SF te tome de la cintura mientras te besa?',
  '¿Alguna vez has enviado un mensaje sexy a Elvis SF sin que lo espere?',
  '¿Te gustaría probar bondage suave con Elvis SF?',
  '¿Te excita la idea de un masaje sensual de Elvis SF?',
  '¿Prefieres hacerlo en la cama o en otro lugar atrevido con Elvis SF?',
  '¿Te atreverías a usar lencería sexy solo para Elvis SF?',
  '¿Te excita la idea de que Elvis SF te vea mientras te desnudas?',
  '¿Alguna vez has pensado en usar juguetes sexuales con Elvis SF?',
  '¿Te gustaría que Elvis SF te sorprendiera con un beso en un lugar público?',
  '¿Prefieres que Elvis SF te acaricie lento o rápido?',
  '¿Te excita que Elvis SF te haga gemir sin tocarte?',
  '¿Has imaginado un juego de temperaturas con hielo o aceite con Elvis SF?',
  '¿Te atreverías a grabar un video hot solo para Elvis SF?',
  '¿Te excita la idea de que Elvis SF te ate suavemente?',
  '¿Prefieres caricias con los ojos vendados con Elvis SF?',
  '¿Alguna vez has fantaseado con un encuentro caliente a media noche con Elvis SF?',
  '¿Te excita que Elvis SF te bese en el cuello y orejas?',
  '¿Te atreverías a probar posiciones atrevidas con Elvis SF?',
  '¿Prefieres hacerlo de pie, sentada o recostada con Elvis SF?',
  '¿Te excita la idea de que Elvis SF te susurre palabras traviesas mientras te besa?',
  '¿Alguna vez has imaginado que Elvis SF te toca debajo de la ropa?',
  '¿Te gustaría un juego de roles hot con Elvis SF en público?',
  '¿Prefieres caricias suaves o intensas en zonas íntimas con Elvis SF?',
  '¿Te atreverías a enviarle fotos atrevidas a Elvis SF solo por diversión?',
  '¿Te excita que Elvis SF te haga un striptease privado?',
  '¿Alguna vez has fantaseado con un encuentro hot sorpresa con Elvis SF?',
  '¿Prefieres iniciar tú o que Elvis SF lo haga?',
  '¿Te excita que Elvis SF te toque mientras ven tu serie favorita?',
  '¿Te atreverías a experimentar con juguetes sexuales con Elvis SF?',
  '¿Prefieres sexo lento y romántico o salvaje y apasionado con Elvis SF?',
  '¿Alguna vez has pensado en un juego de dominación donde Elvis SF manda?',
  '¿Te excita la idea de que Elvis SF te mire desnuda por primera vez?',
  '¿Te atreverías a un beso apasionado en un lugar público con Elvis SF?',
  '¿Prefieres caricias largas o besos ardientes con Elvis SF?',
  '¿Te excita la idea de recibir un mensaje hot inesperado de Elvis SF?',
  '¿Alguna vez has imaginado un encuentro hot mientras llueve con Elvis SF?',
  '¿Te atreverías a probar bondage suave mientras Elvis SF te susurra cosas traviesas?',
  '¿Te atreverías a enviar un video hot a alguien?',
  '¿Cuál es tu fantasía más salvaje?',
  '¿Te gustaría que te tocaran en público?',
  '¿Prefieres hacer un striptease o que te lo hagan?',
  '¿Te excita que te muerdan suavemente?',
  '¿Alguna vez has imaginado un threesome?',
  '¿Te gustaría probar juegos de dominación?',
  '¿Cuál es tu parte favorita del cuerpo para besar?',
  '¿Te excita que te susurren cosas traviesas al oído?',
  '¿Te atreverías a hacer un juego de roles?',
  '¿Prefieres sexo rápido o lento y apasionado?',
  '¿Alguna vez has fantaseado en un lugar prohibido?',
  '¿Te gusta la idea de caricias subidas de tono en la ducha?',
  '¿Has imaginado un beso largo y húmedo?',
  '¿Prefieres dominar o que te dominen?',
  '¿Te excita que te tomen de la cintura mientras te besan?',
  '¿Alguna vez has enviado un mensaje sexy sin que lo espere?',
  '¿Te gustaría probar bondage suave?',
  '¿Te excita la idea de un masaje sensual?',
  '¿Prefieres hacerlo en la cama o en otro lugar atrevido?',
  '¿Te atreverías a usar lencería sexy solo para alguien especial?',
  '¿Te excita que te vean mientras te desnudas?',
  '¿Alguna vez has pensado en usar juguetes sexuales?',
  '¿Te gustaría que te sorprendan con un beso en un lugar público?',
  '¿Prefieres caricias lentas o rápidas?',
  '¿Te excita que te hagan gemir sin tocarte?',
  '¿Has imaginado un juego de temperaturas con hielo o aceite?',
  '¿Te atreverías a grabar un video hot solo para alguien especial?',
  '¿Te excita que te aten suavemente?',
  '¿Prefieres caricias con los ojos vendados?',
  '¿Alguna vez has fantaseado con un encuentro caliente a media noche?',
  '¿Te excita que te besen en el cuello y orejas?',
  '¿Te atreverías a probar posiciones atrevidas?',
  '¿Prefieres hacerlo de pie, sentada o recostada?',
  '¿Te excita que te susurren palabras traviesas mientras te besan?',
  '¿Alguna vez has imaginado que te tocan debajo de la ropa?',
  '¿Te gustaría un juego de roles hot en público?',
  '¿Prefieres caricias suaves o intensas en zonas íntimas?',
  '¿Te atreverías a enviar fotos atrevidas solo por diversión?',
  '¿Te excita que te hagan un striptease privado?',
  '¿Alguna vez has fantaseado con un encuentro hot sorpresa?',
  '¿Prefieres iniciar tú o que lo hagan contigo?',
  '¿Te excita que te toquen mientras ves tu serie favorita?',
  '¿Te atreverías a experimentar con juguetes sexuales?',
  '¿Prefieres sexo lento y romántico o salvaje y apasionado?',
  '¿Alguna vez has pensado en un juego de dominación donde alguien manda?',
  '¿Te excita la idea de que te miren desnuda por primera vez?',
  '¿Te atreverías a un beso apasionado en un lugar público?',
  '¿Prefieres caricias largas o besos ardientes?',
  '¿Te excita la idea de recibir un mensaje hot inesperado?',
  '¿Alguna vez has imaginado un encuentro hot mientras llueve?',
  '¿Te atreverías a probar bondage suave mientras te susurran cosas traviesas?',
  '¿Alguna vez te has sentido tan caliente que casi llamas a los bomberos?',
  '¿Te excita más alguien que ríe de tus desgracias o que las ignora?',
  '¿Prefieres sexo lento o rápido antes de que suene la alarma de incendios?',
  '¿Te gustaría besar a alguien que tiene aliento a cebolla?',
  '¿Alguna vez fantaseaste con alguien que odias?',
  '¿Te atreverías a enviar fotos hot con filtros de zombie?',
  '¿Te excita pensar en alguien mientras lo ignoras cruelmente?',
  '¿Prefieres un masaje sensual o uno que casi te rompa la espalda?',
  '¿Alguna vez has deseado besar a alguien y que se tropiece?',
  '¿Te gustaría probar juguetes sexuales que parezcan armas medievales?',
  '¿Prefieres que alguien te domine o que te ignore mientras te toca?',
  '¿Alguna vez has fantaseado con alguien solo por venganza?',
  '¿Te excita que alguien te mire con cara de psicópata?',
  '¿Te atreverías a un juego de roles donde eres el villano?',
  '¿Prefieres sexo en la cama o en un ataúd (metafórico)?',
  '¿Alguna vez has imaginado besar a alguien que odias en secreto?',
  '¿Te excita que te muerdan con demasiada fuerza?',
  '¿Alguna vez enviaste un mensaje hot solo para molestar a alguien?',
  '¿Prefieres caricias lentas o rápidas con alguien con mala fama?',
  '¿Te excita imaginar sexo mientras llueve ácido (figurativamente)?',
  '¿Alguna vez has fantaseado con alguien que tiene mal aliento extremo?',
  '¿Te atreverías a probar juegos atrevidos en un cementerio vacío?',
  '¿Prefieres que alguien te toque mientras te insulta cariñosamente?',
  '¿Te excita pensar en alguien mientras finge que te odia?',
  '¿Alguna vez has usado humor negro para seducir a alguien?',
  '¿Te gustaría que alguien te toque mientras cuenta chistes macabros?',
  '¿Prefieres hacerlo rápido para sobrevivir o lento para sufrir?',
  '¿Te atreverías a enviar fotos hot con disfraces terroríficos?',
  '¿Alguna vez fantaseaste con sexo en una catástrofe ficticia?',
  '¿Te excita que alguien te mire como si fueras un criminal?',
  '¿Prefieres caricias suaves o intensas mientras alguien te insulta?',
  '¿Te atreverías a probar un beso con sabor a sarcasmo?',
  '¿Alguna vez pensaste en sexo con alguien que nunca soportas?',
  '¿Te excita que alguien te llame monstruo mientras te toca?',
  '¿Prefieres juegos atrevidos o bromas atrevidas mientras tienes sexo?',
  '¿Te atreverías a enviar mensajes picantes en medio de un funeral?',
  '¿Alguna vez imaginaste sexo mientras alguien te amenaza con bromas?',
  '¿Te excita que alguien haga comentarios crueles mientras te besa?',
  '¿Prefieres sexo en silencio o gritos sarcásticos?',
  '¿Te atreverías a probar bondage con alguien que se ríe de tu dolor?',
  '¿Alguna vez fantaseaste con un encuentro hot y un accidente absurdo?',
  '¿Te excita imaginar que alguien te ignora mientras lo deseas?',
  '¿Prefieres caricias lentas o mordiscos juguetones con humor negro?',
  '¿Te atreverías a enviar un video sexy mientras haces un chiste macabro?',
  '¿Alguna vez pensaste en sexo mientras alguien te insulta con creatividad?',
  '¿Te excita que alguien juegue con fuego (figurativo) mientras te toca?',
  '¿Prefieres juegos atrevidos o bromas crueles mientras te besan?',
  '¿Te atreverías a enviar fotos hot con un filtro de cadáver zombie?',
  '¿Alguna vez fantaseaste con un beso peligroso en un lugar prohibido?',
  '¿Te excita que alguien haga comentarios sarcásticos mientras te acaricia?',
  '¿Prefieres dominar o ser dominado mientras alguien se ríe de tus gemidos?',
  '¿Te atreverías a enviar un mensaje hot a alguien que te odia?',
  '¿Alguna vez imaginaste sexo mientras alguien planea una broma pesada?',
  '¿Te excita la idea de caricias atrevidas con un toque de sarcasmo?',
  '¿Eres pobre?',
  '¿Vives con tus papás?',
  '¿Tienes un trabajo que odias?',
  '¿Amas tu vida o la finges en redes sociales?',
  '¿Eres flojo/a?',
  '¿Pasas más tiempo en el celular que trabajando?',
  '¿Has mentido para salir de un compromiso?',
  '¿Eres malo/a administrando dinero?',
  '¿Alguna vez has robado comida?',
  '¿Vives de prestado?',
  '¿Eres adicto/a a las redes sociales?',
  '¿Nunca has pagado una cuenta completa?',
  '¿Eres fanático/a de la vida fácil?',
  '¿Has fingido estar enfermo/a para no ir a trabajar?',
  '¿Eres el típico procrastinador/a?',
  '¿Te da pena admitir tus errores?',
  '¿Alguna vez has plagiado en la escuela o trabajo?',
  '¿Vives del Wi-Fi de otros?',
  '¿Tienes deudas que no quieres pagar?',
  '¿Eres adicto/a a comprar cosas que no necesitas?',
  '¿Has fingido saber de algo que no entendías?',
  '¿Eres impuntual casi siempre?',
  '¿Has llorado por cosas ridículas?',
  '¿Eres de los que juzgan pero no hacen nada?',
  '¿Te das más importancia de la que mereces?',
  '¿Eres dramático/a con cualquier cosa?',
  '¿Alguna vez has mentido para impresionar?',
  '¿Vives pensando en vacaciones que no puedes pagar?',
  '¿Eres el típico que se queja pero nunca cambia nada?',
  '¿Tienes un crush imposible?',
  '¿Te importa más la fama que la amistad?',
  '¿Eres rencoroso/a?',
  '¿Te comparas mucho con otros?',
  '¿Eres adicto/a a los chismes?',
  '¿Alguna vez has ignorado a alguien solo por apariencia?',
  '¿Eres de los que se rinden fácilmente?',
  '¿Tienes hábitos que odias pero no cambias?',
  '¿Eres envidioso/a de lo que no tienes?',
  '¿Alguna vez fingiste ser alguien que no eres?',
  '¿Eres exagerado/a con tus historias?',
  '¿Has dicho que estudias algo que no estudias?',
  '¿Vives según lo que los demás piensan de ti?',
  '¿Eres de los que siempre llegan tarde?',
  '¿Alguna vez has usado excusas ridículas para salir de un plan?',
  '¿Eres dependiente emocionalmente?',
  '¿Alguna vez fingiste gustarte algo que odias?',
  '¿Eres de los que siempre buscan atajos?',
  '¿Te rindes ante los retos más fáciles?',
  '¿Alguna vez te has sentido más inteligente que todos?',
  '¿Eres el típico que critica pero nunca ayuda?',
  '¿Alguna vez has hecho trampa en juegos o retos?',
  '¿Eres de los que no leen instrucciones nunca?',
  '¿Alguna vez dijiste “sí” cuando en realidad querías decir “no”?',
  '¿Eres de los que lloran viendo películas tristes?',
  '¿Alguna vez has fingido entender un tema solo para no parecer tonto/a?'
];